apiVersion: v1
kind: Secret
metadata:
  name: animal-help-secret
  namespace: animal-help-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: "shelter2026"
  JWT_SECRET: "animal_help_app_jwt_secret_k8s_2026"
  DATABASE_URL: "postgresql://postgres:shelter2026@postgres-service:5432/postgres"
