apiVersion: v1
kind: Secret
metadata:
  name: animal-help-secret
  namespace: animal-help-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme"
  DATABASE_URL: "postgresql://postgres:changeme@postgres-service:5432/postgres"
  SSR_CLIENT_SECRET: "changeme"
  B2B_CLIENT_SECRET: "changeme"
  SESSION_SECRET: "changeme"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
