apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-server-images-pvc
  namespace: animal-help-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
